# PyTorch Introduction

## PyTorch Setup

<strong style= "color:red">Pre-requisite </strong>: Working [anaconda](https://www.anaconda.com/products/individual) or [miniconda](https://docs.conda.io/en/latest/miniconda.html) enviorment.

You can install PyTorch on a separate environment or default base environment with an appropriate version from [official website](https://pytorch.org/get-started/locally/). Feel free to create a separate environment using the following commands (minimalistic setup):


`conda create --name dlm-2022 python=3.8.8` (PyTorch is not compatible with the latest version of Python `3.10`. For now, version`3.9.7` or below would do just fine.)

`conda activate dlm-2022` (Feel free to use other names instead of `dlm-2022`)

`pip3 install torch torchvision torchaudio`

`pip3 install notebook`
 
`jupyter notebook`

**`Create a new notebook and have fun!!`**
 
The above steps have been tested on *macOS*, steps may vary for *Windows/Linux*. In case of any irregularities, please refer to the previously mentioned links or reach out to va2134@nyu.edu (or anyone on the course staff). 

You can also remove existing environments using `conda env remove --name dlm-2022`. List existing enviornments: `conda info --envs`

---

**Alternatively:** We have a similar [instruction set](https://github.com/nyumc-dl/BMSC-GA-4493-Spring2020/blob/master/lab1/lab1_pytorch_setup.pdf) from previour iterations of the course.

## Getting Started with PyTorch

In [1]:
import torch
import numpy as np

In [2]:
## PyTorch version
print(torch.__version__)

1.10.1


### Tensors

In [3]:
# Constructing a new uninitialized tensor with given dimensions.
x = torch.Tensor(32, 224, 224, 3) # Defaults to FloatTensor
print(x.size())
x, 

torch.Size([32, 224, 224, 3])


(tensor([[[[0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.],
           ...,
           [0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.]],
 
          [[0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.],
           ...,
           [0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.]],
 
          [[0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.],
           ...,
           [0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.]],
 
          ...,
 
          [[0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.],
           ...,
           [0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.]],
 
          [[0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.],
           ...,
           [0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.]],
 
          [[0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.],
           ...,
           [0., 0., 0.],
           [0., 0., 0.

In [4]:
x = torch.IntTensor(32, 224, 224, 3)
x

tensor([[[[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],

         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],

         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],

         ...,

         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],

         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],

         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]],


        [[[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
          ...,
          [0, 0, 0],
          [0, 0, 0],
     

In [5]:
zeroes = torch.zeros(32, 224, 224, 3) # By default Float values are used, specify arguments for dtype parameter to change data type of tensor
zeroes, zeroes.dtype

(tensor([[[[0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.],
           ...,
           [0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.]],
 
          [[0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.],
           ...,
           [0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.]],
 
          [[0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.],
           ...,
           [0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.]],
 
          ...,
 
          [[0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.],
           ...,
           [0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.]],
 
          [[0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.],
           ...,
           [0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.]],
 
          [[0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.],
           ...,
           [0., 0., 0.],
           [0., 0., 0.

In [6]:
ones = torch.ones(32, 224, 224, 3, dtype=torch.int32) 
ones, ones.dtype

(tensor([[[[1, 1, 1],
           [1, 1, 1],
           [1, 1, 1],
           ...,
           [1, 1, 1],
           [1, 1, 1],
           [1, 1, 1]],
 
          [[1, 1, 1],
           [1, 1, 1],
           [1, 1, 1],
           ...,
           [1, 1, 1],
           [1, 1, 1],
           [1, 1, 1]],
 
          [[1, 1, 1],
           [1, 1, 1],
           [1, 1, 1],
           ...,
           [1, 1, 1],
           [1, 1, 1],
           [1, 1, 1]],
 
          ...,
 
          [[1, 1, 1],
           [1, 1, 1],
           [1, 1, 1],
           ...,
           [1, 1, 1],
           [1, 1, 1],
           [1, 1, 1]],
 
          [[1, 1, 1],
           [1, 1, 1],
           [1, 1, 1],
           ...,
           [1, 1, 1],
           [1, 1, 1],
           [1, 1, 1]],
 
          [[1, 1, 1],
           [1, 1, 1],
           [1, 1, 1],
           ...,
           [1, 1, 1],
           [1, 1, 1],
           [1, 1, 1]]],
 
 
         [[[1, 1, 1],
           [1, 1, 1],
           [1, 1, 1],
        

In [7]:
random = torch.rand(32, 224, 224, 3) # Creates random 
print(random)
print(random.numel(), random.dim()) # Number of Elements, Number of dimensions

tensor([[[[0.7952, 0.3894, 0.0306],
          [0.7971, 0.3652, 0.6804],
          [0.0375, 0.4136, 0.7581],
          ...,
          [0.1701, 0.7019, 0.4028],
          [0.4346, 0.0692, 0.0034],
          [0.2633, 0.7255, 0.1964]],

         [[0.9834, 0.9269, 0.1629],
          [0.5435, 0.2378, 0.4786],
          [0.2775, 0.6205, 0.9979],
          ...,
          [0.5223, 0.1841, 0.9039],
          [0.4480, 0.5466, 0.3868],
          [0.3348, 0.7001, 0.6664]],

         [[0.5346, 0.8876, 0.3334],
          [0.5151, 0.2521, 0.4334],
          [0.6575, 0.1831, 0.3186],
          ...,
          [0.8528, 0.0639, 0.6235],
          [0.1917, 0.6570, 0.0428],
          [0.9711, 0.6035, 0.9075]],

         ...,

         [[0.1171, 0.3293, 0.1366],
          [0.2116, 0.9537, 0.5086],
          [0.5591, 0.5105, 0.0751],
          ...,
          [0.6504, 0.2515, 0.7111],
          [0.9862, 0.5251, 0.5361],
          [0.8470, 0.9341, 0.1218]],

         [[0.7786, 0.6064, 0.4768],
          [0.7430

In [8]:
# Initialize tensor from a list, numpy array
y = torch.tensor([2,3])
y

tensor([2, 3])

In [9]:
# Like Pandas operations return values on new memory and need to reassigned to variable, one can use _ wherever possible to avoid creating new memory.
a = torch.rand(720,420,3)
a.shape
print(a.transpose(0,1).shape)
print(a.shape)
a.transpose_(0,1)
a.shape

torch.Size([420, 720, 3])
torch.Size([720, 420, 3])


torch.Size([420, 720, 3])

In [10]:
print(a)
a.fill_(13)
a

tensor([[[0.1481, 0.4457, 0.7593],
         [0.8645, 0.5124, 0.9868],
         [0.4887, 0.9205, 0.1397],
         ...,
         [0.2796, 0.2798, 0.5747],
         [0.9970, 0.8767, 0.4958],
         [0.6096, 0.5474, 0.2420]],

        [[0.0967, 0.9229, 0.5924],
         [0.2454, 0.1063, 0.8626],
         [0.9188, 0.7749, 0.5680],
         ...,
         [0.0616, 0.2007, 0.8580],
         [0.1164, 0.7846, 0.2903],
         [0.8632, 0.2557, 0.6831]],

        [[0.9266, 0.3053, 0.9418],
         [0.7490, 0.2465, 0.4369],
         [0.9644, 0.9364, 0.1646],
         ...,
         [0.2668, 0.0644, 0.8924],
         [0.8587, 0.6751, 0.2208],
         [0.4247, 0.4733, 0.3840]],

        ...,

        [[0.6650, 0.8529, 0.7703],
         [0.0803, 0.0137, 0.9672],
         [0.1386, 0.4879, 0.4860],
         ...,
         [0.2556, 0.9257, 0.6327],
         [0.0741, 0.2049, 0.3293],
         [0.3106, 0.9019, 0.0393]],

        [[0.8388, 0.0063, 0.4856],
         [0.7866, 0.8218, 0.4520],
         [0.

tensor([[[13., 13., 13.],
         [13., 13., 13.],
         [13., 13., 13.],
         ...,
         [13., 13., 13.],
         [13., 13., 13.],
         [13., 13., 13.]],

        [[13., 13., 13.],
         [13., 13., 13.],
         [13., 13., 13.],
         ...,
         [13., 13., 13.],
         [13., 13., 13.],
         [13., 13., 13.]],

        [[13., 13., 13.],
         [13., 13., 13.],
         [13., 13., 13.],
         ...,
         [13., 13., 13.],
         [13., 13., 13.],
         [13., 13., 13.]],

        ...,

        [[13., 13., 13.],
         [13., 13., 13.],
         [13., 13., 13.],
         ...,
         [13., 13., 13.],
         [13., 13., 13.],
         [13., 13., 13.]],

        [[13., 13., 13.],
         [13., 13., 13.],
         [13., 13., 13.],
         ...,
         [13., 13., 13.],
         [13., 13., 13.],
         [13., 13., 13.]],

        [[13., 13., 13.],
         [13., 13., 13.],
         [13., 13., 13.],
         ...,
         [13., 13., 13.],
        

### Numpy Conversion

In [11]:
x = torch.rand(5)
x.shape

torch.Size([5])

In [13]:
x.numpy()

[0.21395331621170044,
 0.9977781772613525,
 0.2866995930671692,
 0.6415796875953674,
 0.5327841639518738]

In [14]:
x.numpy().tolist()

[0.21395331621170044,
 0.9977781772613525,
 0.2866995930671692,
 0.6415796875953674,
 0.5327841639518738]

### Device

In [15]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [17]:
device,torch.cuda.is_available()

(device(type='cpu'), False)

In [18]:
x.cuda()

AssertionError: Torch not compiled with CUDA enabled

In [19]:
x.to(device)

tensor([0.2140, 0.9978, 0.2867, 0.6416, 0.5328])

### Torch Operations

In [20]:
a = torch.rand(224,224,3)
a.shape

torch.Size([224, 224, 3])

In [23]:
a.unsqueeze(dim=0).shape

torch.Size([1, 224, 224, 3])

In [54]:
y = torch.zeros(32,1)
y[:,0]  = 1

In [55]:
y.squeeze().shape

torch.Size([32])

In [57]:
a = torch.rand(1,2)
b = torch.rand(1,2)
a+b, torch.add(a,b)

(tensor([[0.6351, 1.1698]]), tensor([[0.6351, 1.1698]]))

In [59]:
a.multiply(b)

tensor([[0.0617, 0.3175]])

In [92]:
e = torch.tensor([2.,3.], requires_grad = True)
f = torch.tensor([6.,4.], requires_grad = True)
e,f

(tensor([2., 3.], requires_grad=True), tensor([6., 4.], requires_grad=True))

In [95]:
q = 3*e**3-f**2

In [97]:
q.backward(torch.tensor([1,1]))

In [98]:
e.grad,f.grad

(tensor([36., 81.]), tensor([-12.,  -8.]))

### Loss Functions

In [70]:
import torch.nn as nn
input = torch.randn((4, 5), requires_grad=True)
target = torch.randn(4, 5)

In [71]:
loss = nn.MSELoss()
output = loss(input, target)
output.backward()


In [72]:
output, input

(tensor(1.3349, grad_fn=<MseLossBackward0>),
 tensor([[-1.0660,  1.3172,  0.6221, -0.3381,  0.2244],
         [-1.8411, -0.0944,  0.6590,  0.3364, -0.4110],
         [-0.7328, -1.8434,  0.2786,  1.8064,  1.1056],
         [ 0.1184, -0.7861,  0.3679,  0.7489, -0.4544]], requires_grad=True))